
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TreasureHuntContractArtifactJson from '../../target/treasure_hunt_contract-TreasureHunt.json' with { type: 'json' };
export const TreasureHuntContractArtifact = loadContractArtifact(TreasureHuntContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract TreasureHunt;
 */
export class TreasureHuntContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, TreasureHuntContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): TreasureHuntContract {
    return Contract.at(address, TreasureHuntContract.artifact, wallet) as TreasureHuntContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<TreasureHuntContract>(PublicKeys.default(), wallet, TreasureHuntContractArtifact, (instance, wallet) => TreasureHuntContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<TreasureHuntContract>(publicKeys, wallet, TreasureHuntContractArtifact, (instance, wallet) => TreasureHuntContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TreasureHuntContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TreasureHuntContract['methods'][M]>
  ) {
    return new DeployMethod<TreasureHuntContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TreasureHuntContractArtifact,
      (instance, wallet) => TreasureHuntContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TreasureHuntContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TreasureHuntContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'next_game_id' | 'games' | 'treasures' | 'traps' | 'powers' | 'dig_results'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
next_game_id: {
      slot: new Fr(2n),
    },
games: {
      slot: new Fr(3n),
    },
treasures: {
      slot: new Fr(4n),
    },
traps: {
      slot: new Fr(5n),
    },
powers: {
      slot: new Fr(6n),
    },
dig_results: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'admin' | 'next_game_id' | 'games' | 'treasures' | 'traps' | 'powers' | 'dig_results'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** check_dig_result(game_id: field, dig_x: integer, dig_y: integer) */
    check_dig_result: ((game_id: FieldLike, dig_x: (bigint | number), dig_y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_game() */
    create_game: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** dig(game_id: field, x: integer, y: integer) */
    dig: ((game_id: FieldLike, x: (bigint | number), y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_all_dig_results(game_id: field) */
    get_all_dig_results: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_current_turn(game_id: field) */
    get_current_turn: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_dig_result(game_id: field, x: integer, y: integer) */
    get_dig_result: ((game_id: FieldLike, x: (bigint | number), y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_game(game_id: field) */
    get_game: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_game_status(game_id: field) */
    get_game_status: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_my_powers(game_id: field, player: struct) */
    get_my_powers: ((game_id: FieldLike, player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_game_id() */
    get_next_game_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pending_action(game_id: field) */
    get_pending_action: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_player1(game_id: field) */
    get_player1: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_player1_treasures_found(game_id: field) */
    get_player1_treasures_found: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_player2(game_id: field) */
    get_player2: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_player2_treasures_found(game_id: field) */
    get_player2_treasures_found: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_winner(game_id: field) */
    get_winner: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_game_ready(game_id: field) */
    is_game_ready: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** join_game(game_id: field) */
    join_game: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** place_treasures(game_id: field, x1: integer, y1: integer, x2: integer, y2: integer, x3: integer, y3: integer) */
    place_treasures: ((game_id: FieldLike, x1: (bigint | number), y1: (bigint | number), x2: (bigint | number), y2: (bigint | number), x3: (bigint | number), y3: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** respond_compass(game_id: field, from_x: integer, from_y: integer) */
    respond_compass: ((game_id: FieldLike, from_x: (bigint | number), from_y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** respond_detector(game_id: field, center_x: integer, center_y: integer) */
    respond_detector: ((game_id: FieldLike, center_x: (bigint | number), center_y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** use_compass(game_id: field, from_x: integer, from_y: integer) */
    use_compass: ((game_id: FieldLike, from_x: (bigint | number), from_y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** use_detector(game_id: field, center_x: integer, center_y: integer) */
    use_detector: ((game_id: FieldLike, center_x: (bigint | number), center_y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** use_shovel(game_id: field, old_x: integer, old_y: integer, new_x: integer, new_y: integer) */
    use_shovel: ((game_id: FieldLike, old_x: (bigint | number), old_y: (bigint | number), new_x: (bigint | number), new_y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** use_trap(game_id: field, trap_x: integer, trap_y: integer) */
    use_trap: ((game_id: FieldLike, trap_x: (bigint | number), trap_y: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
